clients_database = "clients"
#clients_database = "http://localhost:8081"

metadata_base_url= "http://127.0.0.1:8080"

[s3]
endpoint_url = "http://localhost:9000"
bucket = "aggregates"
create_bucket = true
access_key_id = "minioadmin"
secret_access_key = "minioadmin"

[mongodb]
server =  "mongodb://localhost/aggregates"
#server = "mongomock://localhost/aggregates"

[mqtt]
broker = "mqtt://localhost"
topic = "aggregates"

[otlp]
spans_endpoint = "http://localhost:4317"
metrics_endpoint = "http://localhost:4317"
insecure = true

[key_cache]
size = 1000
ttl = 300

#[key_cache.redis]
#host = "localhost"
