version: '3'

volumes:
 minio:
 mongo:

services:
  # http://127.0.0.1:9001/
  # minioadmin:minioadmin
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9000:9000/tcp
      - 127.0.0.1:9001:9001/tcp
    volumes:
      - minio:/data
  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017/tcp
    volumes:
      - mongo:/data/db
  vernemq:
    image: vernemq/vernemq
    restart: unless-stopped
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:8888:8888
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_USER
      - DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=4,5
      - DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=-1
      - DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=-1
