volumes:
 minio:
 mongo:

services:
  # http://127.0.0.1:9001/
  # minioadmin:minioadmin
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9000:9000/tcp
      - 127.0.0.1:9001:9001/tcp
    volumes:
      - minio:/data
  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017/tcp
    volumes:
      - mongo:/data/db
  caddy:
    image: caddy:2
    ports:
      - "8081:8081/tcp"
    volumes:
      - ./clients:/data/clients:ro,z
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379/tcp
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:1883:1883/tcp
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
  nats:
    image: nats:latest
    restart: unless-stopped
    command: "--jetstream --http_port 8222"
    ports:
      - 127.0.0.1:4222:4222/tcp
      - 127.0.0.1:8222:8222/tcp
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "8888:8888"  # Prometheus metrics exposed by the collector
      - "8889:8889"  # Prometheus exporter metrics
    configs:
      - source: otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
  jaeger-all-in-one:
    # http://127.0.0.1:16686
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  prometheus:
    # http://127.0.0.1:9090
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus.yaml
        target: /etc/prometheus/prometheus.yml

configs:
  mosquitto.conf:
    content: |
      listener 1883
      allow_anonymous true
  Caddyfile:
    content: |
      http://localhost:8081 {
        encode gzip
        root /data/clients
        file_server
        log {
          output stdout
        }
      }
  otel-collector-config.yaml:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        debug:
          verbosity: detailed
        otlp:
          endpoint: jaeger-all-in-one:4317
          tls:
            insecure: true
        prometheus:
          endpoint: "0.0.0.0:8889"
      processors:
        batch:
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, prometheus]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
  prometheus.yaml:
    content: |
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['otel-collector:8889']
            - targets: ['otel-collector:8888']
