version: '3'

volumes:
 minio:
 mongo:

services:
  # http://127.0.0.1:9001/
  # minioadmin:minioadmin
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9000:9000/tcp
      - 127.0.0.1:9001:9001/tcp
    volumes:
      - minio:/data
  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017/tcp
    volumes:
      - mongo:/data/db
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:1883:1883/tcp
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf

configs:
  mosquitto.conf:
    content: |
      listener 1883
      allow_anonymous true
