CLIENTS_DATABASE = "clients"

METADATA_BASE_URL = "http://127.0.0.1:5000"

S3_ENDPOINT_URL = "http://localhost:9000"
S3_BUCKET = "aggregates"
S3_BUCKET_CREATE = true
S3_ACCESS_KEY_ID = "minioadmin"
S3_SECRET_ACCESS_KEY = "minioadmin"

MONGODB_HOST = "mongodb://localhost/aggregates"

MQTT_BROKER = "localhost"
MQTT_TOPIC = "aggregates"
