[tool.poetry]
name = "aggrec"
version = "0.6.0"
description = "DNS TAPIR Aggregate Receiver"
authors = ["Jakob Schlyter <jakob@kirei.se>"]
readme = "README.md"

[tool.poetry.scripts]
aggrec_server = "aggrec.server:main"
aggrec_client = "aggrec.client:main"

[tool.poetry.dependencies]
python = "^3.11"
mongoengine = "^0.27.0"
http-message-signatures = "^0.4.4"
requests = "^2.30.0"
fastapi = "^0.104.0"
uvicorn = "^0.23.2"
pydantic-settings = "^2.0.3"
werkzeug = "^3.0.1"
boto3 = "^1.26.133"
aiobotocore = "^2.7.0"
aiomqtt = "^1.2.1"
setuptools = "^68.2.2"
jsonformatter = "^0.3.2"
pendulum = "^2.1.2"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
pylama = "^8.4.1"
pytest = "^7.3.1"
pytest-isort = "^3.1.0"
pytest-black = "^0.3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylama.linter.pycodestyle]
max_line_length = 120

[tool.pylama.linter.mccabe]
complexity = 40
