[tool.poetry]
name = "aggrec"
version = "0.7.0"
description = "DNS TAPIR Aggregate Receiver"
authors = ["Jakob Schlyter <jakob@kirei.se>"]
readme = "README.md"

[tool.poetry.scripts]
aggrec_server = "aggrec.server:main"
aggrec_client = "aggrec.client:main"

[tool.poetry.dependencies]
python = "^3.11"
mongoengine = "^0.28.2"
http-message-signatures = "^0.5.0"
requests = "^2.30.0"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
pydantic-settings = "^2.0.3"
werkzeug = "^3.0.1"
boto3 = "^1.26.133"
aiobotocore = "^2.7.0"
aiomqtt = "^2.0.1"
setuptools = "^69.5.1"
jsonformatter = "^0.3.2"
pendulum = "^3"
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
ruff = "^0.4.1"
pytest-ruff = "^0.3.1"
httpx = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
